### ISSUE TITLE
Id Translation number is the same as the Teamviewer plugin

### ISSUE THREAD

**Issue by ovidiox** [PluginsOCSInventory-NG/anydesk#4]
The translation id number 25000 is the same as the Teamviewer plugin, therefore when both extensions or plugins are installed, the Anydesk name does not appear correctly but it appears as "Team Viewer" in the Miscellaneous section.

In my case as a temporary solution I have changed the id 25000 to 25001 in the respective files before installing the plugin:
File: hook.xml
<translation>25000</translation>  -->  <translation>25001</translation> 
languages files: en_GB.txt, fr_FR.txt
25000 --> 25001
file: cd_anydesk.php
print_item_header($l->g(25000));  --> print_item_header($l->g(25001));

**Comment by Lea9250** [comment]
Hi @ovidiox,

The new release of the plugin includes a similar fix. Thank you for bringing it to our attention.

Regards,
Léa
