### ISSUE TITLE
In OCSreports extension's name is "TEAM VIEWER"

### ISSUE THREAD

**Issue by srkxt** [PluginsOCSInventory-NG/anydesk#5]
Hello, the extension is working fine.
But in the OCS reports (Computer -> Miscellaneous) the extension is named "TEAM VIEWER". See [screenshot](http://image.noelshack.com/fichiers/2021/52/1/1640621024-sans-titre.png)

**Comment by caussatjerome** [comment]
[anydesk-master.zip](https://github.com/PluginsOCSInventory-NG/anydesk/files/11981236/anydesk-master.zip)
Mise à jour de l'id language dans les divers fichiers (car c'était le même que pour le module Teamviewer)

**Comment by fbomj** [comment]
Fixed with PR #8
